export const CHECK_NODE_STATUS_START = "CHECK_NODE_STATUS_START";
export const CHECK_NODE_STATUS_SUCCESS = "CHECK_NODE_STATUS_SUCCESS";
export const CHECK_NODE_STATUS_FAILURE = "CHECK_NODE_STATUS_FAILURE";

export const LOAD_BLOCKS_START = "LOAD_BLOCKS_START";
export const LOAD_BLOCKS_SUCCESS = "LOAD_BLOCKS_SUCCESS";
export const LOAD_BLOCKS_FAILURE = "LOAD_BLOCKS_FAILURE";
